spring.application.name: "diffy"
server:
  port: ${http.port:8888}

proxy:
  port: 8880

candidate: "localhost:9000"

master:
  primary: "localhost:9100"
  secondary: "localhost:9200"

service:
  protocol : "http"

serviceName : "Default Sample Service"


spring:
  datasource:
    url: jdbc:h2:file:./data/results.db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update



management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([diffy,%X{trace_id},%X{span_id}]) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %n%wEx"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([diffy,%X{trace_id},%X{span_id}]) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %n%wEx"